version: 0.1
env:
    secrets-manager:
      TOKEN: firstSecret:tokenForSonar
phases:
  build:
    commands:

#Static Application Security Scan (SAST scan) using SonarCloud
     - mvn verify sonar:sonar -Dsonar.projectKey=numeric-application -Dsonar.organization=numeric-application -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b2b70d64a242937c341606ef11faa76a0cfe4d62

